flaskdo/views/user.py
from flask import Flask, request, Blueprint, render_template, redirect, session, url_for
from ..models.user import User

# create a blueprint
bp = Blueprint('user', __name__)


@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    # if HTTP method is GET
    if request.method == 'GET':
        # render the signup template
        return render_template('login/signup.html')
    
    # if HTTP method is POST
    else:
        # read values from the signup form submit
        username = request.form['username']
        email = request.form['email']
        password = request.form['password']
        first_name = request.form['firstName']
        last_name = request.form['lastName']
        address = request.form['address']

        # create a user document
        user = User(first_name=first_name, last_name=last_name,
                    username=username, email = email, password=password, address = address, tasklists=[])
        
        # save the user document
        user.save()
        
        # render the login template
        return redirect('/login')

@bp.route('/login', methods=['GET', 'POST'])
def login():
    # if HTTP method is GET
    if request.method == 'GET':
        # render the login template
        return render_template('login/login.html')
    else:
        # read values from the login form
        username = request.form['username']
        password = request.form['password']

        # get User object based on the filter 'username'
        # User.username (DB) == username (form)
        user = User.query.filter(User.username == username).first()
        
        # check the authentication based on the password from the form
        if user.authenticate(password):
            # add the serialized user object into the session
            session['user'] = user.serialized
            session['my_special_variable'] = 42
            session['is_logged_in'] = True
            
            # render the index template
            return render_template('/index.html')
        
        # redirect to /403
    return render_template('errors/403.html')

@bp.route('/logout')
def logout():
    # clear the session 'user' attribute
    session.clear()
    
    # redirect to /
    return redirect(url_for('home.index'))

@bp.route('/user')
def view_user():
   user = User.query.get_or_404(session['user']['id'])
     
   return render_template('profile/profile.html' ,user=user)


@bp.route('/edit-profile',methods=['GET','POST'])
def edit_user():

    user = User.query.get_or_404(session['user']['id'])
    if request.method=='GET':

        return render_template('profile/edit-profile.html',user=user)

    else:

        username = request.form['username']
        email = request.form['email']
        first_name = request.form['first-name']
        last_name = request.form['last-name']
        address = request.form['address']

        user.username = username
        user.email = email
        user.first_name =   first_name
        user.last_name = last_name
        user.address =  address
        user.save()

    return redirect(url_for('user.view_user'))

 
@bp.route('/user/delete')
def delete_user():
     # retrieve the user
    user = User.query.get_or_404(session['user']['id'])
    
    # delete the user
    user.remove()
    
    # redirect the user to the tasklists
    return render_template('profile/profile.html',user=user)

flaskdo/templates/profile/edit-profile.html
{% extends 'base.html' %}
<!-- Override page title from the template -->
{% block title %}Edit Profile{% endblock %}

<!-- Content block -->
{% block content %} {% if message %}
<div class="mt-3 container">
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Holy guacamole!</strong> {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
{% endif %}
<div class="container">
  <form class="form-signin" method="POST">
    <h1 class="h3 mb-3 font-weight-normal">Edit Profile</h1>
    <label for="email" class="">Email</label>
    <input
      type="text"
      id="email"
      name="email"
      value="{{user['email']}}"
      class="form-control mb-3"
      placeholder="Email"
      required=""
      autofocus=""
    />
    <label for="first-name" class="">First Name</label>
    <input
      type="text"
      id="first-name"
      name="first-name"
      value="{{user['first_name']}}"
      class="form-control mb-3"
      placeholder="First Name"
      required=""
      autofocus=""
    />
    <label for="last-name" class="">Last Name</label>
    <input
      type="text"
      id="last-name"
      name="last-name"
      value="{{user['last_name']}}"
      class="form-control mb-3"
      placeholder="First Name"
      required=""
      autofocus=""
    />
    <label for="birthdate" class="">Birthdate</label>
    <input
      type="date"
      id="birthdate"
      name="birthdate"
      value="{{user['birthdate']}}"
      class="form-control mb-3"
      placeholder="Date"
      autofocus=""
    />
    <label for="avatarURL" class="">Avatar URL</label>
    <input
      type="text"
      id="avatarURL"
      name="avatarURL"
      value="{{user['avatarURL']}}"
      class="form-control mb-3"
      placeholder="Avatar URL"
      autofocus=""
    />
    <label for="address" class="">Address</label>
    <input
      type="text"
      id="address"
      name="address"
      value="{{user['address']}}"
      class="form-control mb-3"
      placeholder="address"
      autofocus=""
    />
    <label for="username" class="">username</label>
    <input
      type="text"
      id="username"
      name="username"
      value="{{user['username']}}"
      class="form-control mb-3"
      placeholder="username"
      autofocus=""
    />
    <label for="email" class="">email</label>
    <input
      type="text"
      id="email"
      name="email"
      value=""
      class="form-control mb-3"
      placeholder="email"
      autofocus=""
    />
    

    <button class="mt-3 btn btn-lg btn-primary btn-block" type="submit">
      Update Profile
    </button>
  </form>0
</div>
{% endblock content %}

flaskdo/templates/profile/profile.html
{% extends 'base.html' %}
<!-- Override page title from the template -->
{% block title %}My Profile{% endblock %}

<!-- Content block -->
{% block content %}

<div class="container py-4">
  <div class="container py-4">
    <div class="card" style="width: 18rem">
      <img src="{{user.avatarURL}}" class="card-img-top" alt="..." />
      <div class="card-body">
        <h5 class="card-title">{{user.first_name}}, {{user.last_name}}</h5>
        <p class="card-text">{{user.username}}</p>
        <a href="{{url_for('user.edit_user')}}" class="btn btn-primary"
          ><svg
            width="1em"
            height="1em"
            viewBox="0 0 16 16"
            class="bi bi-pencil-fill"
            fill="currentColor"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"
            />
            </svg
        ></a>
        <a href="{{url_for('user.edit_user')}}" class="btn btn-primary"
          ><svg
            width="1em"
            height="1em"
            viewBox="0 0 16 16"
            class="bi bi-trash-fill"
            fill="currentColor"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
              />
            </svg
        ></a>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><b>Birthdate:</b> {{user.birthdate}}</li>
        <li class="list-group-item"><b>Address:</b> {{user.address}}</li>
      </ul>
      <div class="card-body">
        <p><b>Task Lists:</b></p>
        <a href="#" class="card-link">Ernie</a>
        <a href="#" class="card-link">Franklin</a>
      </div>
    </div>
    <div></div>
  </div>
</div>
{% endblock %}