flaskdo/views/tasklists.py
from flask import Flask, request, Blueprint, render_template, redirect, session, url_for
from ..models import TaskList, Task, User
from ..core import login_required

# create a blueprint
bp = Blueprint('tasklists', __name__)


@bp.route('/tasklist/create', methods=['GET', 'POST'])
@login_required
def create_tasklist():
    if request.method == 'GET':
        # render the create tasklist template
        return render_template('tasklist/create.html')
    else:
        # read values from the form submit
        name = request.form['list-name']
        description = request.form['list-description']

        # create a tasklist document
        tasklist = TaskList(name = name, description = description, owner_id = session['user']['id'])

        # save the tasklist document
        tasklist.save()

        # get the logged in user
        user = User.query.get_or_404(session['user']['id'])

        # add the newly created tasklist
        user.add_tasklist(str(tasklist.mongo_id))

        # save the changes to the user object
        user.save()

        # update the session
        session['user'] = user.serialized

        # redirect to the index
        return redirect(url_for('tasklists.tasklists'))


@bp.route('/tasklist/<string:tasklist_id>')
@login_required
def view_tasklist(tasklist_id):
    tasklist = TaskList.query.get_or_404(tasklist_id)
    tasks = Task.query.filter(Task.tasklist_id == tasklist_id).all()
    return render_template('tasklist/view.html', tasklist = tasklist, tasks = tasks)

@bp.route('/tasklist/update/<tasklist_id>',methods=['GET','POST'])
@login_required
def update_tasklist(tasklist_id):

    tasklist = TaskList.query.get_or_404(tasklist_id)

    # if the tasklist was found
    if tasklist:
        
        if request.method == 'GET':
            # render the update list form with pre-populated values
            return render_template('tasklist/update-list.html',tasklist=tasklist )
        else:

            # read the values from the update list form
            name = request.form['list-name']
            description = request.form['list-description']

            tasklist.name = name
            tasklist.description = description

            tasklist.save()
           
            # redirect to the 'view_list' view
            return redirect(url_for('tasklists.view_tasklist', tasklist_id=tasklist_id))
    
@bp.route('/tasklist/delete/<string:tasklist_id>')
@login_required
def delete_tasklist(tasklist_id):
    # retrieve the tasklist
    tasklist = TaskList.query.get_or_404(tasklist_id)
    
    # delete the tasklist
    tasklist.remove()
    
    # redirect the user to the tasklists
    return redirect(url_for('tasklists.tasklists'))


@bp.route('/tasklists')
@login_required
def tasklists():   
    # create a list to store the tasklists
    tasklists = TaskList.query.filter(TaskList.owner_id == session['user']['id'])

    
    # render the task lists template
    return render_template('tasklist/task-lists.html', tasklists = tasklists)

@bp.route('/search', methods=['GET','POST'])
def search():
    if request.method=='GET':
        return render_template('search/search.html')
    else:    

        search_keyword = request.form['search-keyword']

        # search_results = Task.query.filter(Task.title.like('%' + search_keyword+ '%')).all()
        search_results = Task.query.filter(
            {
                '$or': [
                    {Task.title: {"$regex": search_keyword}},
                    {Task.description: {"$regex": search_keyword}}
                ]       
            }
            ).all()

        print(search_results,search_keyword)
          
        return render_template('search/results.html',results=search_results,keyword=search_keyword)

@bp.route('/favorites' ,methods=['GET'])
def view_favorites():

    if request.method=='GET':
        favorites_tasklists = TaskList.query.filter(
            {
                '$and': [
                    {TaskList.owner_id:session['user']['id'] },
                    {TaskList.is_favorite:True}
                ]       
            }
            ).all()


        return render_template('tasklist/favorites.html',tasklists=favorites_tasklists)

@bp.route('/private' ,methods=['GET'])
def view_private():

    if request.method=='GET':
        private_tasklists = TaskList.query.filter(
            {
                '$and': [
                    {TaskList.owner_id:session['user']['id'] },
                    {TaskList.is_private:True}
                ]       
            }
            ).all()


        return render_template('tasklist/private.html',tasklists=private_tasklists)



@bp.route('/favorite/<tasklist_id>')    
def set_favorite(tasklist_id):
    
    tasklist =TaskList.query.get_or_404(tasklist_id)

    if tasklist.is_favorite == True:

        tasklist.is_favorite = False
    else:
        tasklist.is_favorite = True

    tasklist.save()
    return redirect('/favorites')  

@bp.route('/tasklist/private/<tasklist_id>',methods=['GET','POST'])    
def mark_private(tasklist_id):

    tasklist =TaskList.query.get_or_404(tasklist_id)

    if tasklist.is_private == True :

        tasklist.is_private = False
    else:

        tasklist.is_private = True

    tasklist.save()

    return redirect('/private')   

@bp.route('/overdue/tasklist/<tasklist_id>', methods =['GET'])
@login_required
def view_overdue(tasklist_id  ):
    tasklists = TaskList.query.filter(TaskList.owner_id == session['user']['id'])
    # if request.method == 'GET':
    #     return render_template('tasklist/overdue.html',tasklists=tasklists)
    print(tasklists)
            
    return render_template('index.html', tasklists =tasklists , tasklist_id =tasklist_id )

    


 

flaskdo/views/user.py
from flask import Flask, request, Blueprint, render_template, redirect, session, url_for
from ..models.user import User

# create a blueprint
bp = Blueprint('user', __name__)


@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    # if HTTP method is GET
    if request.method == 'GET':
        # render the signup template
        return render_template('login/signup.html')
    
    # if HTTP method is POST
    else:
        # read values from the signup form submit
        username = request.form['username']
        email = request.form['email']
        password = request.form['password']
        first_name = request.form['firstName']
        last_name = request.form['lastName']
        address = request.form['address']

        # create a user document
        user = User(first_name=first_name, last_name=last_name,
                    username=username, email = email, password=password, address = address, tasklists=[])
        
        # save the user document
        user.save()
        
        # render the login template
        return redirect('/login')

@bp.route('/login', methods=['GET', 'POST'])
def login():
    # if HTTP method is GET
    if request.method == 'GET':
        # render the login template
        return render_template('login/login.html')
    else:
        # read values from the login form
        username = request.form['username']
        password = request.form['password']

        # get User object based on the filter 'username'
        # User.username (DB) == username (form)
        user = User.query.filter(User.username == username).first()
        
        # check the authentication based on the password from the form
        if user.authenticate(password):
            # add the serialized user object into the session
            session['user'] = user.serialized
            session['my_special_variable'] = 42
            session['is_logged_in'] = True
            
            # render the index template
            return render_template('/index.html')
        
        # redirect to /403
    return render_template('errors/403.html')

@bp.route('/logout')
def logout():
    # clear the session 'user' attribute
    session.clear()
    
    # redirect to /
    return redirect(url_for('home.index'))

@bp.route('/user')
def view_user():
   user = User.query.get_or_404(session['user']['id'])
     
   return render_template('profile/profile.html' ,user=user)


@bp.route('/edit-profile',methods=['GET','POST'])
def edit_user():

    user = User.query.get_or_404(session['user']['id'])
    if request.method=='GET':

        return render_template('profile/edit-profile.html',user=user)

    else:

        username = request.form['username']
        email = request.form['email']
        first_name = request.form['first-name']
        last_name = request.form['last-name']
        address = request.form['address']

        user.username = username
        user.email = email
        user.first_name =   first_name
        user.last_name = last_name
        user.address =  address
        user.save()

    return redirect(url_for('user.view_user'))

 
@bp.route('/user/delete')
def delete_user():
     # retrieve the user
    user = User.query.get_or_404(session['user']['id'])
    
    # delete the user
    user.remove()
    
    # redirect the user to the tasklists
    return render_template('profile/profile.html',user=user)

flaskdo/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% block head %}
    <meta charset="utf-8" />
    <title>{% block title %}FlaskDo{% endblock %}</title>
    <link
      rel="icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='favicon.ico') }}"
    />

    {% block styles %}
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="/static/css/global.css"
      crossorigin="anonymous"
    />

    {% endblock %} {% endblock %}
  </head>
  <body class="d-flex flex-column h-100">
    <!-- navigation section -->
    <header
      class="navbar navbar-expand navbar-dark bg-dark box-shadow sticky-top"
    >
      <a class="navbar-brand" href="/">FlaskDo</a>
      <div class="navbar-nav-scroll">
        {% if session['is_logged_in'] %}
        <ul class="navbar-nav bd-navbar-nav flex-row">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('tasklists.tasklists')}}"
              >Lists</a
          >
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="">Tasks</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{url_for('tasklists.search')}}">Search</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{url_for('tasklists.view_favorites')}}">Favorites</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="">Private List</a>
          </li>
          
        </ul> 
      </div>
      <ul class="navbar-nav ml-md-auto">
        <li class="nav-item dropdown">
          <a
            class="nav-item nav-link dropdown-toggle mr-md-2"
            href="#"
            id="bd-versions"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            Hello, {{session['user']['first_name']}}!
          </a>
          <div
            class="dropdown-menu dropdown-menu-md-right"
            aria-labelledby="bd-versions"
          >
            <a class="dropdown-item" href="{{url_for('user.view_user',user_id=session['user']['id'])}}">View_user(Profile)</a>
            <a class="dropdown-item" href="/">Change Password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/logout">Logout</a>
          </div>
        </li>
      </ul>
      {% endif %}
    </header>
    <!-- header section -->

    <header
      class="d-flex flex-column flex-md-row align-items-md-center p-5 bg-light"
    >
      <div class="pt-md-3 pb-md-4">
        <h1 class="bd-title mt-0">
          {% block header_title%}FlaskDo{% endblock %}
        </h1>
        <p class="bd-lead">
          {% block header_subtitle%} A simple To-Do list to get you started.
          Quickly add a list for your next project. Remember what you need to
          buy. Share lists with the people who matter. {% endblock %}
        </p>
        {% block actions %}
        <div class="d-flex flex-column flex-sm-row">
          <a
            href="{{url_for('user.login')}}"
            class="btn btn-outline-secondary py-2 px-3"
            >Login</a
          >
          <a
            href="{{url_for('user.signup')}}"
            class="btn btn-outline-secondary py-2 px-3 mt-3 mt-sm-0 ml-sm-3"
            >Sign up</a
          >
          
        </div>
        {% endblock %}
      </div>
      
    </header>

    <!-- main section -->
    <main>
      {% for message in get_flashed_messages() %}
      <div class="container">
        <div
          class="alert alert-warning alert-dismissible fade show"
          role="alert"
        >
          <strong>Holy guacamole!</strong> {{message}}
          <button
            type="button"
            class="close"
            data-dismiss="alert"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
      {% endfor %}
      <div>{% block content %}{% endblock %}</div>
    </main>

    <!-- footer section -->
    <footer class="my-5 pt-5 text-muted text-center text-small">
      <p class="mb-1">© 2020 FlaskDo</p>
      <ul class="list-inline">
        <li class="list-inline-item"><a href="#">Privacy</a></li>
        <li class="list-inline-item"><a href="#">Terms</a></li>
        <li class="list-inline-item"><a href="#">Support</a></li>
      </ul>
    </footer>
    {% block scripts %}
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>

    {% endblock %}
  </body>
</html>

flaskdo/templates/index.html
{% extends 'base.html' %}
<!-- content block -->
{% block content %} {% if session['is_logged_in'] %}
<html lang="en"><head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v4.1.1">
  <title>Jumbotron Template · Bootstrap</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/jumbotron/">

  <!-- Bootstrap core CSS -->
<link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.5/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <!-- Custom styles for this template -->
  <link href="jumbotron.css" rel="stylesheet">
</head>
<body>

<main role="main">

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Welcome,
      {{session['user']['first_name'] | capitalize}}!</h1>
    
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
  </div>
</div>

<div class="container mt-4">
  <!-- Example row of columns -->
  <div class="justify-content-md-center">
    <ul
      class="nav nav-pills nav-justified pills-grey"
      id="myTab"
      role="tablist"
    >
      <li class="nav-item" role="presentation">
        <a
          class="nav-link active"
          id="tasklists"
          data-toggle="tab"
          href=""
          role="tab"
          aria-controls="home"
          aria-selected="true"
          
          >Overdue</a>
          <h1>{{session['user']['tasklists']}}</h1>
          
      </li>
      <li class="nav-item" role="presentation">
        <a
          class="nav-link"
          id="profile-tab"
          data-toggle="tab"
          href="#profile"
          role="tab"
          aria-controls="profile"
          aria-selected="false"
          >Due Today</a
        >
      </li>
      <li class="nav-item" role="presentation">
        <a
          class="nav-link"
          id="contact-tab"
          data-toggle="tab"
          href="#contact"
          role="tab"
          aria-controls="contact"
          aria-selected="false"
          >Due This Week</a
        >
      </li>
    </ul>
 

</main>

<footer class="container">

</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/docs/4.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>

</body></html>


{% endif %} 
</body>

</html>
{% endblock %}

flaskdo/templates/session.html
<p><b>The value of the 'user' key in the session is:</b></p>
{{session['user']}}
<p><b>The value of the 'is_logged_in' key in the session is:</b></p>
{{session['is_logged_in']}}
<p><b>The value of the 'my_special_variable' key in the session is:</b></p>
{{session['my_special_variable']}}

<p>
  <b
    >Hello, {{session['user']['first_name'] | capitalize}}
    {{session['user']['last_name']| capitalize}}!</b
  >
</p>

<p>
  <b>Your username is: {{session['user']['username']}}</b>
</p>