flaskdo/models/tasklist.py
from ..core.database import db
from datetime import datetime


class TaskList(db.Document):
    name = db.StringField()
    description = db.StringField()
    owner_id = db.StringField()
    created_at = db.DateTimeField(default=datetime.utcnow())
    is_favorite = db.BoolField(default=False)
    is_private = db.BoolField(default=False)

flaskdo/views/task.py
from flask import Flask, request, Blueprint, render_template, redirect, session, url_for
from ..models import Task
from ..core import login_required

# create a blueprint
bp = Blueprint('task', __name__)

@bp.route('/task/create/<string:tasklist_id>', methods=['GET', 'POST'])
@login_required
def create_task(tasklist_id):
    if request.method == 'GET':
        # render the create task template
        return render_template('task/create.html')
    else:
        # read values from the form submit
        title = request.form['task-title']
        description = request.form['task-description']

        # create a task document
        task = Task(title = title, description = description, tasklist_id = tasklist_id)


        # save the tasklist document
        task.save()
        print(title,description)
        
        # redirect to the index
        return redirect(url_for('tasklists.view_tasklist', tasklist_id = tasklist_id))

@bp.route('/task/<string:tasklist_id>/<string:task_id>')
@login_required
def view_task(tasklist_id,task_id):
  
    task = Task.query.get_or_404(task_id)
    
    return render_template('tasks/view-task.html', task = task)
    
@bp.route('/task/update/<tasklist_id>/<string:task_id>',methods=['GET','POST'])
@login_required
def update_task(tasklist_id,task_id):

    task = Task.query.get_or_404(task_id)

    # if the tasklist was found
    if task:
        
        if request.method == 'GET':
            # render the update list form with pre-populated values
            return render_template('tasks/update-task.html',task=task )
        else:

            # read the values from the update list form
            title = request.form['task-title']
            description = request.form['task-description']

            task.title= title
            task.description = description

            task.save()
           
            # redirect to the 'view_list' view
            return render_template('index.html', tasklist_id = tasklist_id,task_id=task_id)

@bp.route('/task/delete/<string:tasklist_id>/<string:task_id>', methods=['GET'])
@login_required
def delete_task(tasklist_id, task_id):
    task = Task.query.get_or_404(task_id)
    task.remove()

    # redirect to the index
    return redirect(url_for('tasklists.view_tasklist', tasklist_id = tasklist_id))

flaskdo/views/tasklists.py
from flask import Flask, request, Blueprint, render_template, redirect, session, url_for
from ..models import TaskList, Task, User
from ..core import login_required

# create a blueprint
bp = Blueprint('tasklists', __name__)


@bp.route('/tasklist/create', methods=['GET', 'POST'])
@login_required
def create_tasklist():
    if request.method == 'GET':
        # render the create tasklist template
        return render_template('tasklist/create.html')
    else:
        # read values from the form submit
        name = request.form['list-name']
        description = request.form['list-description']

        # create a tasklist document
        tasklist = TaskList(name = name, description = description, owner_id = session['user']['id'])

        # save the tasklist document
        tasklist.save()

        # get the logged in user
        user = User.query.get_or_404(session['user']['id'])

        # add the newly created tasklist
        user.add_tasklist(str(tasklist.mongo_id))

        # save the changes to the user object
        user.save()

        # update the session
        session['user'] = user.serialized

        # redirect to the index
        return redirect(url_for('tasklists.tasklists'))


@bp.route('/tasklist/<string:tasklist_id>')
@login_required
def view_tasklist(tasklist_id):
    tasklist = TaskList.query.get_or_404(tasklist_id)
    tasks = Task.query.filter(Task.tasklist_id == tasklist_id).all()
    return render_template('tasklist/view.html', tasklist = tasklist, tasks = tasks)

@bp.route('/tasklist/update/<tasklist_id>',methods=['GET','POST'])
@login_required
def update_tasklist(tasklist_id):

    tasklist = TaskList.query.get_or_404(tasklist_id)

    # if the tasklist was found
    if tasklist:
        
        if request.method == 'GET':
            # render the update list form with pre-populated values
            return render_template('tasklist/update-list.html',tasklist=tasklist )
        else:

            # read the values from the update list form
            name = request.form['list-name']
            description = request.form['list-description']

            tasklist.name = name
            tasklist.description = description

            tasklist.save()
           
            # redirect to the 'view_list' view
            return redirect(url_for('tasklists.view_tasklist', tasklist_id=tasklist_id))
    
@bp.route('/tasklist/delete/<string:tasklist_id>')
@login_required
def delete_tasklist(tasklist_id):
    # retrieve the tasklist
    tasklist = TaskList.query.get_or_404(tasklist_id)
    
    # delete the tasklist
    tasklist.remove()
    
    # redirect the user to the tasklists
    return redirect(url_for('tasklists.tasklists'))


@bp.route('/tasklists')
@login_required
def tasklists():   
    # create a list to store the tasklists
    tasklists = TaskList.query.filter(TaskList.owner_id == session['user']['id'])

    
    # render the task lists template
    return render_template('tasklist/task-lists.html', tasklists = tasklists)

@bp.route('/search', methods=['GET','POST'])
def search():
    if request.method=='GET':
        return render_template('search/search.html')
    else:    

        search_keyword = request.form['search-keyword']

        # search_results = Task.query.filter(Task.title.like('%' + search_keyword+ '%')).all()
        search_results = Task.query.filter(
            {
                '$or': [
                    {Task.title: {"$regex": search_keyword}},
                    {Task.description: {"$regex": search_keyword}}
                ]       
            }
            ).all()

        print(search_results,search_keyword)
          
        return render_template('search/results.html',results=search_results,keyword=search_keyword)

@bp.route('/favorites' ,methods=['GET'])
def view_favorites():

    if request.method=='GET':
        favorites_tasklists = TaskList.query.filter(
            {
                '$and': [
                    {TaskList.owner_id:session['user']['id'] },
                    {TaskList.is_favorite:True}
                ]       
            }
            ).all()


        return render_template('tasklist/favorites.html',tasklists=favorites_tasklists)

@bp.route('/private' ,methods=['GET'])
def view_private():

    if request.method=='GET':
        private_tasklists = TaskList.query.filter(
            {
                '$and': [
                    {TaskList.owner_id:session['user']['id'] },
                    {TaskList.is_private:True}
                ]       
            }
            ).all()


        return render_template('tasklist/private.html',tasklists=private_tasklists)



@bp.route('/favorite/<tasklist_id>')    
def set_favorite(tasklist_id):
    
    tasklist =TaskList.query.get_or_404(tasklist_id)

    if tasklist.is_favorite == True:

        tasklist.is_favorite = False
    else:
        tasklist.is_favorite = True

    tasklist.save()
    return redirect('/favorites')  

@bp.route('/tasklist/private/<tasklist_id>',methods=['GET','POST'])    
def mark_private(tasklist_id):

    tasklist =TaskList.query.get_or_404(tasklist_id)

    if tasklist.is_private == True :

        tasklist.is_private = False
    else:

        tasklist.is_private = True

    tasklist.save()

    return redirect('/private')   

@bp.route('/overdue/tasklist/<tasklist_id>', methods =['GET'])
@login_required
def view_overdue(tasklist_id  ):
    tasklists = TaskList.query.filter(TaskList.owner_id == session['user']['id'])
    # if request.method == 'GET':
    #     return render_template('tasklist/overdue.html',tasklists=tasklists)
    print(tasklists)
            
    return render_template('index.html', tasklists =tasklists , tasklist_id =tasklist_id )

    


 

flaskdo/templates/tasklist/create.html
{% extends 'base.html' %}
<!-- header title block -->
{% block header_title%}Create a Task List{% endblock%}
<!-- header subtitle block -->
{% block header_subtitle %} Create and view your task lists!{% endblock %}
<!-- actions block -->
{% block actions %} {% endblock %}

<!-- Content block -->
{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-12 order-md-1">
      <form class="form-signin" method="POST">
        <label for="inputTaskListName" class="sr-only">Task List Name</label>
        <input
          type="text"
          id="inputTaskListName"
          name="list-name"
          class="form-control mb-3"
          placeholder="Enter a name for your task list"
          required=""
          autofocus=""
        />
        <label for="textAreaTaskListDescription" class="sr-only"
          >Task List Description</label
        >
        <textarea
          id="textAreaTaskListDescription"
          name="list-description"
          class="form-control mb-3"
          placeholder="Enter a description for your task list"
        >
        </textarea>
        

        <button class="btn btn-lg btn-secondary btn-block" type="submit">
          Create Task List
        </button>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

flaskdo/templates/tasklist/favorites.html
{% extends 'base.html' %}
<!-- header title block -->
{% block header_title%}Favorites Lists{% endblock%}
<!-- header subtitle block -->
{% block header_subtitle %}  view your Favorites lists!{% endblock %}
<!-- actions block -->
{% block actions %}

{% endblock %}
<!-- content block -->
{% block content %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      {% for list in tasklists %}

      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img
            class="card-img-top"
            data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text={{list.name}}"
            alt="Thumbnail [100%x225]"
            style="height: 225px; width: 100%; display: block"
            src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1748e00f135%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1748e00f135%22%3E%3Crect%20width%3D%22348%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22116.7109375%22%20y%3D%22120.15%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
            data-holder-rendered="true"
          />
          <div class="card-body">
            <h5 class="card-title">{{list.name}}</h5>
            <p class="card-text">{{list.description}}</p>
            
            <p class="card-text">{{list.created_at}}</p>

            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a
                  href="{{url_for('tasklists.view_tasklist', tasklist_id = list.mongo_id)}}"
                  class="btn btn-sm btn-outline-secondary"
                  ><svg
                    width="1em"
                    height="1em"
                    viewBox="0 0 16 16"
                    class="bi bi-eye-fill"
                    fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                    <path
                      fill-rule="evenodd"
                      d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"
                    /></svg
                ></a>
                <a
                  href="{{url_for('tasklists.update_tasklist', tasklist_id = list.mongo_id)}}"
                  class="btn btn-sm btn-outline-secondary"
                  ><svg
                    width="1em"
                    height="1em"
                    viewBox="0 0 16 16"
                    class="bi bi-pencil-fill"
                    fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"
                    /></svg
                ></a>

                <a href="{{url_for('tasklists.set_favorite',tasklist_id=list.mongo_id)}}" class="btn btn-sm btn-outline-secondary"
                  ><svg
                    width="1em"
                    height="1em"
                    viewBox="0 0 16 16"
                    class="bi bi-star"
                    fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.523-3.356c.329-.314.158-.888-.283-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767l-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288l1.847-3.658 1.846 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.564.564 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"
                    /></svg
                ></a>
              </div>
              <small class="text-muted">9 mins</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

flaskdo/templates/tasklist/task-lists.html
{% extends 'base.html' %}
<!-- header title block -->
{% block header_title%}Task Lists{% endblock%}
<!-- header subtitle block -->
{% block header_subtitle %} Create and view your task lists!{% endblock %}
<!-- actions block -->
{% block actions %}
<div class="d-flex flex-column flex-sm-row">
  <a
    href="{{url_for('tasklists.create_tasklist')}}"
    class="btn btn-outline-secondary py-2 px-3 mt-3 mt-sm-0 ml-sm-3"
    >Create Task List</a
  >
</div>

{% endblock %}
<!-- content block -->
{% block content %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      {% for list in tasklists %}

      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img
            class="card-img-top"
            data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text={{list.name}}"
            alt="Thumbnail [100%x225]"
            style="height: 225px; width: 100%; display: block"
            src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1748e00f135%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1748e00f135%22%3E%3Crect%20width%3D%22348%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22116.7109375%22%20y%3D%22120.15%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
            data-holder-rendered="true"
          />
          <div class="card-body">
            <h5 class="card-title">{{list.name}}</h5>
            <p class="card-text">{{list.description}}</p>
            
            <p class="card-text">{{list.created_at}}</p>

            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a
                  href="{{url_for('tasklists.view_tasklist', tasklist_id = list.mongo_id)}}"
                  class="btn btn-sm btn-outline-secondary"
                  ><svg
                    width="1em"
                    height="1em"
                    viewBox="0 0 16 16"
                    class="bi bi-eye-fill"
                    fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                    <path
                      fill-rule="evenodd"
                      d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"
                    /></svg
                ></a>
                <a
                  href="{{url_for('tasklists.update_tasklist', tasklist_id = list.mongo_id)}}"
                  class="btn btn-sm btn-outline-secondary"
                  ><svg
                    width="1em"
                    height="1em"
                    viewBox="0 0 16 16"
                    class="bi bi-pencil-fill"
                    fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"
                    /></svg
                ></a>
                <a
                  href="{{url_for('tasklists.delete_tasklist', tasklist_id = list.mongo_id)}}"
                  class="btn btn-sm btn-outline-secondary"
                  ><svg
                    width="1em"
                    height="1em"
                    viewBox="0 0 16 16"
                    class="bi bi-trash-fill"
                    fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"
                    /></svg
                ></a>
                <a href="" class="btn btn-sm btn-outline-secondary"
                  ><svg
                    width="1em"
                    height="1em"
                    viewBox="0 0 16 16"
                    class="bi bi-star"
                    fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.523-3.356c.329-.314.158-.888-.283-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767l-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288l1.847-3.658 1.846 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.564.564 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"
                    /></svg
                ></a>
              </div>
              <small class="text-muted">9 mins</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

flaskdo/templates/tasklist/view.html
{% extends 'base.html' %}

<!-- header title block -->
{% block header_title%} {{tasklist['name']}} {% endblock%}
<!-- header subtitle block -->
{% block header_subtitle %} {{tasklist['description']}}{% endblock %}
<!-- actions block -->
{% block actions %} {% endblock %}
<!-- content block -->
{% block content %}
<div class="container-fluid">
  <h1 class="py-4"></h1>
  <h4 class="py-4"></h4>
  <div class="container py-2">
    <div class="row justify-content-between">
      <div class="col-md-8 mb-3">
        <h3>Tasks</h3>
      </div>
      <div class="col-md-4 mb-3">
        <!-- Button trigger modal -->
        <a
          href="{{url_for('task.create_task', tasklist_id = tasklist['mongo_id'])}}"
          class="btn btn-secondary"
          >+</a
        >
      </div>
    </div>
    <div class="row justify-content-between">
      <div class="col-md-12 mb-3">
        {% if tasks %}
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Description</th>
              <th scope="col">Time</th>

              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for task in tasks %}
            <tr>
              <th scope="row">{{loop.index}}</th>
              <td>{{task.title}}</td>
              <td>{{task.description}}</td>
              <td>{{task.created_at}}</td>


              <td>
                <a href="{{url_for('task.view_task',tasklist_id = tasklist['mongo_id'],  task_id = task.mongo_id)}}" class="btn btn-sm btn-outline-secondary"
                  ><svg
                    width="1em"
                    height="1em"
                    viewBox="0 0 16 16"
                    class="bi bi-eye-fill"
                    fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                    <path
                      fill-rule="evenodd"
                      d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"
                    /></svg
                ></a>
                <a href="{{url_for('task.update_task',tasklist_id = tasklist['mongo_id'], task_id = task.mongo_id)}}" class="btn btn-sm btn-outline-secondary"
                  ><svg
                    width="1em"
                    height="1em"
                    viewBox="0 0 16 16"
                    class="bi bi-pencil-fill"
                    fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"
                    /></svg
                ></a>
                <a
                  href="{{url_for('task.delete_task', tasklist_id = tasklist['mongo_id'], task_id = task.mongo_id)}}"
                  class="btn btn-sm btn-outline-secondary"
                  ><svg
                    width="1em"
                    height="1em"
                    viewBox="0 0 16 16"
                    class="bi bi-trash-fill"
                    fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"
                    /></svg
                ></a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <h5>This list has no tasks.</h5>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock%}